# Generated by Django 3.1.7 on 2021-03-18 13:05

import appOne.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_auto_20210318_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(default=1, upload_to=appOne.models.get_image_filename, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
